# contestID
contestID = "0000000000051705" # 2019 qualification round
# contestID = "0000000000007883" # Round 1A 2018

# list of friends' handle
handles = [
    "henrybear327", 
    "Andychen", 
    "amoshyc", 
    "BeMg", 
    "teatea", 
    "aaaaajack", 
    "mi.", 
    "Chi.", 
    "allenwhale", 
    "betaveros",
    "morrisy",
    "dreamoon_love_AA"] 

# refresh interval in second
refreshInterval = 60 